
package com.knight.servico;

import com.knight.modelo.Livro;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Livros", targetNamespace = "http://servico.knight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Livros {


    /**
     * 
     * @return
     *     returns java.util.List<com.knight.servico.Livro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarLivros", targetNamespace = "http://servico.knight.com/", className = "com.knight.servico.ListarLivros")
    @ResponseWrapper(localName = "listarLivrosResponse", targetNamespace = "http://servico.knight.com/", className = "com.knight.servico.ListarLivrosResponse")
    @Action(input = "http://servico.knight.com/Livros/listarLivrosRequest", output = "http://servico.knight.com/Livros/listarLivrosResponse")
    public List<Livro> listarLivros();

}
