
package com.knight.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LivrosOrigemService", targetNamespace = "http://servico.knight.com/", wsdlLocation = "http://localhost:8090/livros?wsdl")
public class LivrosOrigemService
    extends Service
{

    private final static URL LIVROSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIVROSSERVICE_EXCEPTION;
    private final static QName LIVROSSERVICE_QNAME = new QName("http://servico.knight.com/", "LivrosOrigemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/livros?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVROSSERVICE_WSDL_LOCATION = url;
        LIVROSSERVICE_EXCEPTION = e;
    }

    public LivrosOrigemService() {
        super(__getWsdlLocation(), LIVROSSERVICE_QNAME);
    }

    public LivrosOrigemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVROSSERVICE_QNAME, features);
    }

    public LivrosOrigemService(URL wsdlLocation) {
        super(wsdlLocation, LIVROSSERVICE_QNAME);
    }

    public LivrosOrigemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVROSSERVICE_QNAME, features);
    }

    public LivrosOrigemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivrosOrigemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LivrosOrigem
     */
    @WebEndpoint(name = "LivrosOrigemPort")
    public Livros getLivrosPort() {
        return super.getPort(new QName("http://servico.knight.com/", "LivrosOrigemPort"), Livros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LivrosOrigem
     */
    @WebEndpoint(name = "LivrosOrigemPort")
    public Livros getLivrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.knight.com/", "LivrosOrigemPort"), Livros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVROSSERVICE_EXCEPTION!= null) {
            throw LIVROSSERVICE_EXCEPTION;
        }
        return LIVROSSERVICE_WSDL_LOCATION;
    }

}
